### ISSUE TITLE
API Error preventing uploading of files

### ISSUE THREAD

**Issue by dillfrescott** [with-labs/popspace#21]
```
[2023-11-19T10:50:43.880] [ERROR] app - Unexpected API error /upload_file: {} TypeError: Cannot read properties of undefined (reading 'thumbnailUrl')
    at Object.createFileMetadata (/usr/src/app/noodle-api/src/lib/files.js:18:38)
    at FileManager.<anonymous> (/usr/src/app/file-upload/dist/FileManager.js:105:95)
    at step (/usr/src/app/file-upload/dist/FileManager.js:33:23)
    at Object.next (/usr/src/app/file-upload/dist/FileManager.js:14:53)
    at fulfilled (/usr/src/app/file-upload/dist/FileManager.js:5:58)
```

**Comment by dillfrescott** [comment]
Worked on this a bit.

See: https://github.com/with-labs/popspace/pull/22

**Comment by dillfrescott** [comment]
As well as a prebuilt docker container with the fixes: [here](https://git.dill.moe/cross/-/packages/container/popspace/latest)

**Comment by a-type** [comment]
Thanks. Change is merged. I really need to set up some automated CI on this project, but I'm not sure how that works when the owning organization is defunct.

**Comment by dillfrescott** [comment]
You could always fork it under your account and take it over I guess!

**Comment by lobau** [comment]
> Thanks. Change is merged. I really need to set up some automated CI on this project, but I'm not sure how that works when the owning organization is defunct.

Let me know if we should discuss governance. Happy to fork it out of withlabs to my account, your account, or anybody else :)
